unbind -a

set -g prefix C-Space
bind C-Space send-prefix

bind -n C-w select-pane -U
bind -n C-a select-pane -L
bind -n C-s select-pane -D
bind -n C-d select-pane -R

bind -n C-z previous-window
bind -n C-x next-window

bind -n C-p command-prompt "rename-window '%%'"
bind -n C-l new-window
bind -n C-q kill-window


# enable status bar
set -g status on
set -g status-position bottom

set -g status-style "bg=#603DA8,fg=#FFE8FF"


# refresh every second (needed for unix time)
set -g status-interval 1

# left empty
set -g status-left ""
set -g status-left-length 0

# windows in the middle (default behavior)
setw -g window-status-format "<#W>"
setw -g window-status-current-format "[#W]"

# unix time on the right
set -g status-right "%m-%d %H:%M:%S"
set -g status-right-length 20

# evil
set -g mouse on
